if [ ! -f application-exit.svg ]; then echo application-exit.svg ; fi
if [ ! -f application-rss+xml.svg ]; then echo application-rss+xml.svg ; fi
if [ ! -f application-x-mswinurl.svg ]; then echo application-x-mswinurl.svg ; fi
if [ ! -f checked.svg ]; then echo checked.svg ; fi
if [ ! -f checking.svg ]; then echo checking.svg ; fi
if [ ! -f collapse.svg ]; then echo collapse.svg ; fi
if [ ! -f completed.svg ]; then echo completed.svg ; fi
if [ ! -f configure.svg ]; then echo configure.svg ; fi
if [ ! -f connected.svg ]; then echo connected.svg ; fi
if [ ! -f dialog-cancel.svg ]; then echo dialog-cancel.svg ; fi
if [ ! -f dialog-information.svg ]; then echo dialog-information.svg ; fi
if [ ! -f dialog-warning.svg ]; then echo dialog-warning.svg ; fi
if [ ! -f disconnected.svg ]; then echo disconnected.svg ; fi
if [ ! -f document-edit-verify.svg ]; then echo document-edit-verify.svg ; fi
if [ ! -f document-edit.svg ]; then echo document-edit.svg ; fi
if [ ! -f document-encrypt.svg ]; then echo document-encrypt.svg ; fi
if [ ! -f document-import.svg ]; then echo document-import.svg ; fi
if [ ! -f document-new.svg ]; then echo document-new.svg ; fi
if [ ! -f document-properties.svg ]; then echo document-properties.svg ; fi
if [ ! -f document-save.svg ]; then echo document-save.svg ; fi
if [ ! -f download.svg ]; then echo download.svg ; fi
if [ ! -f downloading.svg ]; then echo downloading.svg ; fi
if [ ! -f downloading_small.svg ]; then echo downloading_small.svg ; fi
if [ ! -f edit-clear-history.svg ]; then echo edit-clear-history.svg ; fi
if [ ! -f edit-clear.svg ]; then echo edit-clear.svg ; fi
if [ ! -f edit-copy.svg ]; then echo edit-copy.svg ; fi
if [ ! -f edit-cut.svg ]; then echo edit-cut.svg ; fi
if [ ! -f edit-delete.svg ]; then echo edit-delete.svg ; fi
if [ ! -f edit-find-user.svg ]; then echo edit-find-user.svg ; fi
if [ ! -f edit-find.svg ]; then echo edit-find.svg ; fi
if [ ! -f edit-paste.svg ]; then echo edit-paste.svg ; fi
if [ ! -f edit-rename.svg ]; then echo edit-rename.svg ; fi
if [ ! -f error.svg ]; then echo error.svg ; fi
if [ ! -f expand.svg ]; then echo expand.svg ; fi
if [ ! -f fileicon.svg ]; then echo fileicon.svg ; fi
if [ ! -f filteractive.svg ]; then echo filteractive.svg ; fi
if [ ! -f filterall.svg ]; then echo filterall.svg ; fi
if [ ! -f filterinactive.svg ]; then echo filterinactive.svg ; fi
if [ ! -f filterstalled.svg ]; then echo filterstalled.svg ; fi
if [ ! -f firewalled.svg ]; then echo firewalled.svg ; fi
if [ ! -f folder-documents.svg ]; then echo folder-documents.svg ; fi
if [ ! -f folder-download.svg ]; then echo folder-download.svg ; fi
if [ ! -f folder-new.svg ]; then echo folder-new.svg ; fi
if [ ! -f folder-remote.svg ]; then echo folder-remote.svg ; fi
if [ ! -f gear.svg ]; then echo gear.svg ; fi
if [ ! -f gear32.svg ]; then echo gear32.svg ; fi
if [ ! -f go-bottom.svg ]; then echo go-bottom.svg ; fi
if [ ! -f go-down.svg ]; then echo go-down.svg ; fi
if [ ! -f go-top.svg ]; then echo go-top.svg ; fi
if [ ! -f go-up.svg ]; then echo go-up.svg ; fi
if [ ! -f help-about.svg ]; then echo help-about.svg ; fi
if [ ! -f help-contents.svg ]; then echo help-contents.svg ; fi
if [ ! -f inode-directory.svg ]; then echo inode-directory.svg ; fi
if [ ! -f insert-link.svg ]; then echo insert-link.svg ; fi
if [ ! -f kt-magnet.svg ]; then echo kt-magnet.svg ; fi
if [ ! -f kt-set-max-download-speed.svg ]; then echo kt-set-max-download-speed.svg ; fi
if [ ! -f kt-set-max-upload-speed.svg ]; then echo kt-set-max-upload-speed.svg ; fi
if [ ! -f list-add.svg ]; then echo list-add.svg ; fi
if [ ! -f list-remove.svg ]; then echo list-remove.svg ; fi
if [ ! -f loading.png ]; then echo loading.png ; fi
if [ ! -f mail-folder-inbox.svg ]; then echo mail-folder-inbox.svg ; fi
if [ ! -f mail-mark-read.svg ]; then echo mail-mark-read.svg ; fi
if [ ! -f mascot.png ]; then echo mascot.png ; fi
if [ ! -f media-playback-pause.svg ]; then echo media-playback-pause.svg ; fi
if [ ! -f media-playback-start.svg ]; then echo media-playback-start.svg ; fi
if [ ! -f media-seek-forward.svg ]; then echo media-seek-forward.svg ; fi
if [ ! -f network-server.svg ]; then echo network-server.svg ; fi
if [ ! -f network-wired.svg ]; then echo network-wired.svg ; fi
if [ ! -f object-locked.svg ]; then echo object-locked.svg ; fi
if [ ! -f office-chart-line.svg ]; then echo office-chart-line.svg ; fi
if [ ! -f paused.svg ]; then echo paused.svg ; fi
if [ ! -f preferences-desktop.svg ]; then echo preferences-desktop.svg ; fi
if [ ! -f preferences-other.svg ]; then echo preferences-other.svg ; fi
if [ ! -f preferences-system-network.svg ]; then echo preferences-system-network.svg ; fi
if [ ! -f preferences-web-browser-cookies.svg ]; then echo preferences-web-browser-cookies.svg ; fi
if [ ! -f qbittorrent-tray-dark.svg ]; then echo qbittorrent-tray-dark.svg ; fi
if [ ! -f qbittorrent-tray-light.svg ]; then echo qbittorrent-tray-light.svg ; fi
if [ ! -f qbittorrent-tray-with-font.svg ]; then echo qbittorrent-tray-with-font.svg ; fi
if [ ! -f qbittorrent-tray.svg ]; then echo qbittorrent-tray.svg ; fi
if [ ! -f qbittorrent.ico ]; then echo qbittorrent.ico ; fi
if [ ! -f qbittorrent_file.ico ]; then echo qbittorrent_file.ico ; fi
if [ ! -f queued.svg ]; then echo queued.svg ; fi
if [ ! -f ratio.svg ]; then echo ratio.svg ; fi
if [ ! -f resumed.svg ]; then echo resumed.svg ; fi
if [ ! -f rss-config.svg ]; then echo rss-config.svg ; fi
if [ ! -f security-high.svg ]; then echo security-high.svg ; fi
if [ ! -f security-low.svg ]; then echo security-low.svg ; fi
if [ ! -f seeding.svg ]; then echo seeding.svg ; fi
if [ ! -f services.svg ]; then echo services.svg ; fi
if [ ! -f slow.svg ]; then echo slow.svg ; fi
if [ ! -f slow_off.svg ]; then echo slow_off.svg ; fi
if [ ! -f speedometer.svg ]; then echo speedometer.svg ; fi
if [ ! -f sphere.png ]; then echo sphere.png ; fi
if [ ! -f sphere2.png ]; then echo sphere2.png ; fi
if [ ! -f splash.png ]; then echo splash.png ; fi
if [ ! -f stalledDL.svg ]; then echo stalledDL.svg ; fi
if [ ! -f stalledUP.svg ]; then echo stalledUP.svg ; fi
if [ ! -f system-log-out.svg ]; then echo system-log-out.svg ; fi
if [ ! -f tab-close.svg ]; then echo tab-close.svg ; fi
if [ ! -f task-attention.svg ]; then echo task-attention.svg ; fi
if [ ! -f task-complete.svg ]; then echo task-complete.svg ; fi
if [ ! -f task-ongoing.svg ]; then echo task-ongoing.svg ; fi
if [ ! -f task-reject.svg ]; then echo task-reject.svg ; fi
if [ ! -f text-plain.svg ]; then echo text-plain.svg ; fi
if [ ! -f tools-report-bug.svg ]; then echo tools-report-bug.svg ; fi
if [ ! -f unavailable.svg ]; then echo unavailable.svg ; fi
if [ ! -f uploading.svg ]; then echo uploading.svg ; fi
if [ ! -f user-group-delete.svg ]; then echo user-group-delete.svg ; fi
if [ ! -f user-group-new.svg ]; then echo user-group-new.svg ; fi
if [ ! -f view-calendar-journal.svg ]; then echo view-calendar-journal.svg ; fi
if [ ! -f view-categories.svg ]; then echo view-categories.svg ; fi
if [ ! -f view-filter.svg ]; then echo view-filter.svg ; fi
if [ ! -f view-preview.svg ]; then echo view-preview.svg ; fi
if [ ! -f view-refresh.svg ]; then echo view-refresh.svg ; fi
if [ ! -f view-statistics.svg ]; then echo view-statistics.svg ; fi
if [ ! -f wallet-open.svg ]; then echo wallet-open.svg ; fi
if [ ! -f webui.svg ]; then echo webui.svg ; fi